name = "imsdashboard"
main = "src/app/api/[[route]]/route.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "imsdashboard-prod"

[env.staging]
name = "imsdashboard-staging"

[[d1_databases]]
binding = "DB"
database_name = "imsdashboard-db"
database_id = "427e0283-4eb2-4430-8111-fff046afbbb2"

[env.production.d1_databases]
binding = "DB"
database_name = "imsdashboard-db"
database_id = "427e0283-4eb2-4430-8111-fff046afbbb2"

[env.staging.d1_databases]
binding = "DB"
database_name = "imsdashboard-db"
database_id = "427e0283-4eb2-4430-8111-fff046afbbb2"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = ".next/static"

[env.production.site]
bucket = ".next/static"

[env.staging.site]
bucket = ".next/static"
